' easy.plantuml
'
' 你可以将下面的语句放在你的PlantUML源代码的@startuml/@enduml之间，
' 这样就可以使用EasyPlantUML项目中针对PlantUML的通用的优化功能部份：
'
'     !include easy.plantuml
'
' 也可以根据你要绘制的图表，将有针对性的优化功能集合到你的源代码中：
'
'     !include easy.plantuml!activity
'     !include easy.plantuml!activity_beta
'     !include easy.plantuml!class
'     !include easy.plantuml!component
'     !include easy.plantuml!deployment
'     !include easy.plantuml!object
'     !include easy.plantuml!sequence
'     !include easy.plantuml!timing
'     !include easy.plantuml!state
'     !include easy.plantuml!usecase
'     !include easy.plantuml!archimate
'     !include easy.plantuml!gantt
'     !include easy.plantuml!salt
'
' 如果你要使用保存在网络上的EasyPlantUML库，则需要在!include之前先定义
' EASYPLANTUML_BASEURL的值，例如：
'
'     !define EASYPLANTUML_BASEURL https://raw.githubusercontent.com/keqiongpan/EasyPlantUML/master/Sources
'     !include EASYPLANTUML_BASEURL/easy.plantuml
'

@startuml (id=base)
!define EASYPLANTUML_ALLINONE
!ifdef EASYPLANTUML_BASEURL
!ifdef EASYPLANTUML_ALLINONE
!includeurl EASYPLANTUML_BASEURL/easy.allinone.plantuml!_common
!includeurl EASYPLANTUML_BASEURL/easy.allinone.plantuml!_repeat
!else
!includeurl EASYPLANTUML_BASEURL/common.plantuml
!includeurl EASYPLANTUML_BASEURL/repeat.plantuml
!endif
!else
!ifdef EASYPLANTUML_ALLINONE
!include easy.allinone.plantuml!_common
!include easy.allinone.plantuml!_repeat
!else
!include common.plantuml
!include repeat.plantuml
!endif
!endif
@enduml

@startuml (id=activity)
!define _ACTIVITY_DIAGRAM_
!ifdef EASYPLANTUML_BASEURL
!ifdef EASYPLANTUML_ALLINONE
!includeurl EASYPLANTUML_BASEURL/easy.allinone.plantuml!base
!else
!includeurl EASYPLANTUML_BASEURL/easy.plantuml!base
!endif
!else
!ifdef EASYPLANTUML_ALLINONE
!include easy.allinone.plantuml!base
!else
!include easy.plantuml!base
!endif
!endif
@enduml

@startuml (id=activity_beta)
!define _ACTIVITY_BETA_DIAGRAM_
!ifdef EASYPLANTUML_BASEURL
!ifdef EASYPLANTUML_ALLINONE
!includeurl EASYPLANTUML_BASEURL/easy.allinone.plantuml!base
!else
!includeurl EASYPLANTUML_BASEURL/easy.plantuml!base
!endif
!else
!ifdef EASYPLANTUML_ALLINONE
!include easy.allinone.plantuml!base
!else
!include easy.plantuml!base
!endif
!endif
@enduml

@startuml (id=class)
!define _CLASS_DIAGRAM_
!ifdef EASYPLANTUML_BASEURL
!ifdef EASYPLANTUML_ALLINONE
!includeurl EASYPLANTUML_BASEURL/easy.allinone.plantuml!base
!else
!includeurl EASYPLANTUML_BASEURL/easy.plantuml!base
!endif
!else
!ifdef EASYPLANTUML_ALLINONE
!include easy.allinone.plantuml!base
!else
!include easy.plantuml!base
!endif
!endif
@enduml

@startuml (id=component)
!define _COMPONENT_DIAGRAM_
!ifdef EASYPLANTUML_BASEURL
!ifdef EASYPLANTUML_ALLINONE
!includeurl EASYPLANTUML_BASEURL/easy.allinone.plantuml!base
!else
!includeurl EASYPLANTUML_BASEURL/easy.plantuml!base
!endif
!else
!ifdef EASYPLANTUML_ALLINONE
!include easy.allinone.plantuml!base
!else
!include easy.plantuml!base
!endif
!endif
@enduml

@startuml (id=deployment)
!define _DEPLOYMENT_DIAGRAM_
!ifdef EASYPLANTUML_BASEURL
!ifdef EASYPLANTUML_ALLINONE
!includeurl EASYPLANTUML_BASEURL/easy.allinone.plantuml!base
!else
!includeurl EASYPLANTUML_BASEURL/easy.plantuml!base
!endif
!else
!ifdef EASYPLANTUML_ALLINONE
!include easy.allinone.plantuml!base
!else
!include easy.plantuml!base
!endif
!endif
@enduml

@startuml (id=object)
!define _OBJECT_DIAGRAM_
!ifdef EASYPLANTUML_BASEURL
!ifdef EASYPLANTUML_ALLINONE
!includeurl EASYPLANTUML_BASEURL/easy.allinone.plantuml!base
!else
!includeurl EASYPLANTUML_BASEURL/easy.plantuml!base
!endif
!else
!ifdef EASYPLANTUML_ALLINONE
!include easy.allinone.plantuml!base
!else
!include easy.plantuml!base
!endif
!endif
@enduml

@startuml (id=sequence)
!define _SEQUENCE_DIAGRAM_
!ifdef EASYPLANTUML_BASEURL
!ifdef EASYPLANTUML_ALLINONE
!includeurl EASYPLANTUML_BASEURL/easy.allinone.plantuml!base
!else
!includeurl EASYPLANTUML_BASEURL/easy.plantuml!base
!endif
!else
!ifdef EASYPLANTUML_ALLINONE
!include easy.allinone.plantuml!base
!else
!include easy.plantuml!base
!endif
!endif
@enduml

@startuml (id=timing)
!define _TIMING_DIAGRAM_
!ifdef EASYPLANTUML_BASEURL
!ifdef EASYPLANTUML_ALLINONE
!includeurl EASYPLANTUML_BASEURL/easy.allinone.plantuml!base
!else
!includeurl EASYPLANTUML_BASEURL/easy.plantuml!base
!endif
!else
!ifdef EASYPLANTUML_ALLINONE
!include easy.allinone.plantuml!base
!else
!include easy.plantuml!base
!endif
!endif
@enduml

@startuml (id=state)
!define _STATE_DIAGRAM_
!ifdef EASYPLANTUML_BASEURL
!ifdef EASYPLANTUML_ALLINONE
!includeurl EASYPLANTUML_BASEURL/easy.allinone.plantuml!base
!else
!includeurl EASYPLANTUML_BASEURL/easy.plantuml!base
!endif
!else
!ifdef EASYPLANTUML_ALLINONE
!include easy.allinone.plantuml!base
!else
!include easy.plantuml!base
!endif
!endif
@enduml

@startuml (id=usecase)
!define _USECASE_DIAGRAM_
!ifdef EASYPLANTUML_BASEURL
!ifdef EASYPLANTUML_ALLINONE
!includeurl EASYPLANTUML_BASEURL/easy.allinone.plantuml!base
!else
!includeurl EASYPLANTUML_BASEURL/easy.plantuml!base
!endif
!else
!ifdef EASYPLANTUML_ALLINONE
!include easy.allinone.plantuml!base
!else
!include easy.plantuml!base
!endif
!endif
@enduml

@startuml (id=archimate)
!define _ARCHIMATE_DIAGRAM_
!ifdef EASYPLANTUML_BASEURL
!ifdef EASYPLANTUML_ALLINONE
!includeurl EASYPLANTUML_BASEURL/easy.allinone.plantuml!base
!else
!includeurl EASYPLANTUML_BASEURL/easy.plantuml!base
!endif
!else
!ifdef EASYPLANTUML_ALLINONE
!include easy.allinone.plantuml!base
!else
!include easy.plantuml!base
!endif
!endif
@enduml

@startuml (id=gantt)
!define _GANTT_DIAGRAM_
!ifdef EASYPLANTUML_BASEURL
!ifdef EASYPLANTUML_ALLINONE
!includeurl EASYPLANTUML_BASEURL/easy.allinone.plantuml!base
!else
!includeurl EASYPLANTUML_BASEURL/easy.plantuml!base
!endif
!else
!ifdef EASYPLANTUML_ALLINONE
!include easy.allinone.plantuml!base
!else
!include easy.plantuml!base
!endif
!endif
@enduml

@startuml (id=salt)
!define _SALT_DIAGRAM_
!ifdef EASYPLANTUML_BASEURL
!ifdef EASYPLANTUML_ALLINONE
!includeurl EASYPLANTUML_BASEURL/easy.allinone.plantuml!base
!includeurl EASYPLANTUML_BASEURL/easy.allinone.plantuml!_salt
!else
!includeurl EASYPLANTUML_BASEURL/easy.plantuml!base
!includeurl EASYPLANTUML_BASEURL/salt.plantuml
!endif
!else
!ifdef EASYPLANTUML_ALLINONE
!include easy.allinone.plantuml!base
!include easy.allinone.plantuml!_salt
!else
!include easy.plantuml!base
!include salt.plantuml
!endif
!endif
@enduml

@startuml (id=_common)

' 回车换行，例如salt图：{# top _ bottom}。
!definelong _


!enddefinelong

@enduml

@startuml (id=_repeat)

' 重复指定的内容context若干次，并以分隔符separator进行分隔。
' 例如： _3(egg) 。

!ifdef _SALT_DIAGRAM_

!define _0(x,d='|')
!define _1(x,d='|') ##x
!define _2(x,d='|') ##x##d##x
!define _3(x,d='|') ##x##d##x##d##x
!define _4(x,d='|') ##x##d##x##d##x##d##x
!define _5(x,d='|') ##x##d##x##d##x##d##x##d##x
!define _6(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x
!define _7(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _8(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _9(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _10(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _11(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _12(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _13(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _14(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _15(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _16(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _17(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _18(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _19(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _20(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _21(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _22(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _23(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _24(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _25(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _26(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _27(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _28(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _29(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _30(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _31(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _32(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _33(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _34(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _35(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _36(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _37(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _38(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _39(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _40(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _41(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _42(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _43(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _44(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _45(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _46(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _47(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _48(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _49(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _50(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _51(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _52(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _53(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _54(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _55(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _56(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _57(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _58(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _59(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _60(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _61(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _62(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _63(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _64(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _65(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _66(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _67(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _68(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _69(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _70(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _71(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _72(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _73(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _74(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _75(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _76(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _77(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _78(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _79(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _80(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _81(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _82(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _83(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _84(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _85(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _86(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _87(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _88(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _89(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _90(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _91(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _92(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _93(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _94(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _95(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _96(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _97(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _98(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _99(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _100(x,d='|') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x

!else

!define _0(x,d='')
!define _1(x,d='') ##x
!define _2(x,d='') ##x##d##x
!define _3(x,d='') ##x##d##x##d##x
!define _4(x,d='') ##x##d##x##d##x##d##x
!define _5(x,d='') ##x##d##x##d##x##d##x##d##x
!define _6(x,d='') ##x##d##x##d##x##d##x##d##x##d##x
!define _7(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _8(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _9(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _10(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _11(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _12(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _13(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _14(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _15(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _16(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _17(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _18(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _19(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _20(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _21(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _22(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _23(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _24(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _25(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _26(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _27(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _28(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _29(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _30(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _31(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _32(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _33(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _34(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _35(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _36(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _37(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _38(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _39(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _40(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _41(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _42(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _43(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _44(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _45(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _46(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _47(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _48(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _49(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _50(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _51(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _52(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _53(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _54(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _55(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _56(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _57(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _58(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _59(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _60(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _61(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _62(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _63(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _64(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _65(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _66(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _67(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _68(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _69(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _70(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _71(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _72(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _73(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _74(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _75(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _76(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _77(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _78(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _79(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _80(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _81(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _82(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _83(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _84(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _85(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _86(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _87(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _88(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _89(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _90(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _91(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _92(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _93(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _94(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _95(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _96(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _97(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _98(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _99(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x
!define _100(x,d='') ##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x##d##x

!endif

@enduml

@startuml (id=_salt)

' 将内部元素作为一个整体对待。
!define one {
!define eno }

' 将内部元素作为一个平板对待。
!define pad { . _ { . | . | . | {
!define dap } | . | . | . } _ . }

' 为独立元素添加一层外边框线。
!define sex {+ one
!define xes eno }

' 为平板元素添加一层外边框线。
!define box {+ pad
!define xob dap }

' 标签
!define label(title) title

' 按钮
!define button(title) [title]
!define submit(title = '  提交  ') button(title)
!define ok(title = '  确定  ') button(title)
!define cancel(title = '  取消  ') button(title)
!define close(title = '  关闭  ') button(title)
!define yes(title = '  是  ') button(title)
!define no(title = '  否  ') button(title)

' 文本输入框
!define textfield(value = '                ') "value"
!define textview(value = '.|.|.|.|.|.|.|.') sex { value } | . | . | . _ . xes

' 单选框/复选框
!define checked 'X'
!define unchecked ' '
!define radiobox(title, value = ' ') (value) title
!define checkbox(title, value = ' ') [value] title

' 下拉选择框
!define combobox(value = '                ') ^value^

@enduml
