@startuml (id=repeat)

' 重复指定的内容context若干次，并以分隔符separator进行分隔。
' 例如： _3(egg) 。

!ifdef _SALT_DIAGRAM_

!define _0(context, separator = '|')
!define _1(context, separator = '|') context
!define _2(context, separator = '|') _1(context, separator) separator context
!define _3(context, separator = '|') _2(context, separator) separator context
!define _4(context, separator = '|') _3(context, separator) separator context
!define _5(context, separator = '|') _4(context, separator) separator context
!define _6(context, separator = '|') _5(context, separator) separator context
!define _7(context, separator = '|') _6(context, separator) separator context
!define _8(context, separator = '|') _7(context, separator) separator context
!define _9(context, separator = '|') _8(context, separator) separator context
!define _10(context, separator = '|') _9(context, separator) separator context
!define _11(context, separator = '|') _10(context, separator) separator context
!define _12(context, separator = '|') _11(context, separator) separator context
!define _13(context, separator = '|') _12(context, separator) separator context
!define _14(context, separator = '|') _13(context, separator) separator context
!define _15(context, separator = '|') _14(context, separator) separator context
!define _16(context, separator = '|') _15(context, separator) separator context
!define _17(context, separator = '|') _16(context, separator) separator context
!define _18(context, separator = '|') _17(context, separator) separator context
!define _19(context, separator = '|') _18(context, separator) separator context
!define _20(context, separator = '|') _19(context, separator) separator context
!define _21(context, separator = '|') _20(context, separator) separator context
!define _22(context, separator = '|') _21(context, separator) separator context
!define _23(context, separator = '|') _22(context, separator) separator context
!define _24(context, separator = '|') _23(context, separator) separator context
!define _25(context, separator = '|') _24(context, separator) separator context
!define _26(context, separator = '|') _25(context, separator) separator context
!define _27(context, separator = '|') _26(context, separator) separator context
!define _28(context, separator = '|') _27(context, separator) separator context
!define _29(context, separator = '|') _28(context, separator) separator context
!define _30(context, separator = '|') _29(context, separator) separator context
!define _31(context, separator = '|') _30(context, separator) separator context
!define _32(context, separator = '|') _31(context, separator) separator context
!define _33(context, separator = '|') _32(context, separator) separator context
!define _34(context, separator = '|') _33(context, separator) separator context
!define _35(context, separator = '|') _34(context, separator) separator context
!define _36(context, separator = '|') _35(context, separator) separator context
!define _37(context, separator = '|') _36(context, separator) separator context
!define _38(context, separator = '|') _37(context, separator) separator context
!define _39(context, separator = '|') _38(context, separator) separator context
!define _40(context, separator = '|') _39(context, separator) separator context
!define _41(context, separator = '|') _40(context, separator) separator context
!define _42(context, separator = '|') _41(context, separator) separator context
!define _43(context, separator = '|') _42(context, separator) separator context
!define _44(context, separator = '|') _43(context, separator) separator context
!define _45(context, separator = '|') _44(context, separator) separator context
!define _46(context, separator = '|') _45(context, separator) separator context
!define _47(context, separator = '|') _46(context, separator) separator context
!define _48(context, separator = '|') _47(context, separator) separator context
!define _49(context, separator = '|') _48(context, separator) separator context
!define _50(context, separator = '|') _49(context, separator) separator context
!define _51(context, separator = '|') _50(context, separator) separator context
!define _52(context, separator = '|') _51(context, separator) separator context
!define _53(context, separator = '|') _52(context, separator) separator context
!define _54(context, separator = '|') _53(context, separator) separator context
!define _55(context, separator = '|') _54(context, separator) separator context
!define _56(context, separator = '|') _55(context, separator) separator context
!define _57(context, separator = '|') _56(context, separator) separator context
!define _58(context, separator = '|') _57(context, separator) separator context
!define _59(context, separator = '|') _58(context, separator) separator context
!define _60(context, separator = '|') _59(context, separator) separator context
!define _61(context, separator = '|') _60(context, separator) separator context
!define _62(context, separator = '|') _61(context, separator) separator context
!define _63(context, separator = '|') _62(context, separator) separator context
!define _64(context, separator = '|') _63(context, separator) separator context
!define _65(context, separator = '|') _64(context, separator) separator context
!define _66(context, separator = '|') _65(context, separator) separator context
!define _67(context, separator = '|') _66(context, separator) separator context
!define _68(context, separator = '|') _67(context, separator) separator context
!define _69(context, separator = '|') _68(context, separator) separator context
!define _70(context, separator = '|') _69(context, separator) separator context
!define _71(context, separator = '|') _70(context, separator) separator context
!define _72(context, separator = '|') _71(context, separator) separator context
!define _73(context, separator = '|') _72(context, separator) separator context
!define _74(context, separator = '|') _73(context, separator) separator context
!define _75(context, separator = '|') _74(context, separator) separator context
!define _76(context, separator = '|') _75(context, separator) separator context
!define _77(context, separator = '|') _76(context, separator) separator context
!define _78(context, separator = '|') _77(context, separator) separator context
!define _79(context, separator = '|') _78(context, separator) separator context
!define _80(context, separator = '|') _79(context, separator) separator context
!define _81(context, separator = '|') _80(context, separator) separator context
!define _82(context, separator = '|') _81(context, separator) separator context
!define _83(context, separator = '|') _82(context, separator) separator context
!define _84(context, separator = '|') _83(context, separator) separator context
!define _85(context, separator = '|') _84(context, separator) separator context
!define _86(context, separator = '|') _85(context, separator) separator context
!define _87(context, separator = '|') _86(context, separator) separator context
!define _88(context, separator = '|') _87(context, separator) separator context
!define _89(context, separator = '|') _88(context, separator) separator context
!define _90(context, separator = '|') _89(context, separator) separator context
!define _91(context, separator = '|') _90(context, separator) separator context
!define _92(context, separator = '|') _91(context, separator) separator context
!define _93(context, separator = '|') _92(context, separator) separator context
!define _94(context, separator = '|') _93(context, separator) separator context
!define _95(context, separator = '|') _94(context, separator) separator context
!define _96(context, separator = '|') _95(context, separator) separator context
!define _97(context, separator = '|') _96(context, separator) separator context
!define _98(context, separator = '|') _97(context, separator) separator context
!define _99(context, separator = '|') _98(context, separator) separator context
!define _100(context, separator = '|') _99(context, separator) separator context

!else

!define _0(context, separator = '')
!define _1(context, separator = '') context
!define _2(context, separator = '') _1(context, separator) separator context
!define _3(context, separator = '') _2(context, separator) separator context
!define _4(context, separator = '') _3(context, separator) separator context
!define _5(context, separator = '') _4(context, separator) separator context
!define _6(context, separator = '') _5(context, separator) separator context
!define _7(context, separator = '') _6(context, separator) separator context
!define _8(context, separator = '') _7(context, separator) separator context
!define _9(context, separator = '') _8(context, separator) separator context
!define _10(context, separator = '') _9(context, separator) separator context
!define _11(context, separator = '') _10(context, separator) separator context
!define _12(context, separator = '') _11(context, separator) separator context
!define _13(context, separator = '') _12(context, separator) separator context
!define _14(context, separator = '') _13(context, separator) separator context
!define _15(context, separator = '') _14(context, separator) separator context
!define _16(context, separator = '') _15(context, separator) separator context
!define _17(context, separator = '') _16(context, separator) separator context
!define _18(context, separator = '') _17(context, separator) separator context
!define _19(context, separator = '') _18(context, separator) separator context
!define _20(context, separator = '') _19(context, separator) separator context
!define _21(context, separator = '') _20(context, separator) separator context
!define _22(context, separator = '') _21(context, separator) separator context
!define _23(context, separator = '') _22(context, separator) separator context
!define _24(context, separator = '') _23(context, separator) separator context
!define _25(context, separator = '') _24(context, separator) separator context
!define _26(context, separator = '') _25(context, separator) separator context
!define _27(context, separator = '') _26(context, separator) separator context
!define _28(context, separator = '') _27(context, separator) separator context
!define _29(context, separator = '') _28(context, separator) separator context
!define _30(context, separator = '') _29(context, separator) separator context
!define _31(context, separator = '') _30(context, separator) separator context
!define _32(context, separator = '') _31(context, separator) separator context
!define _33(context, separator = '') _32(context, separator) separator context
!define _34(context, separator = '') _33(context, separator) separator context
!define _35(context, separator = '') _34(context, separator) separator context
!define _36(context, separator = '') _35(context, separator) separator context
!define _37(context, separator = '') _36(context, separator) separator context
!define _38(context, separator = '') _37(context, separator) separator context
!define _39(context, separator = '') _38(context, separator) separator context
!define _40(context, separator = '') _39(context, separator) separator context
!define _41(context, separator = '') _40(context, separator) separator context
!define _42(context, separator = '') _41(context, separator) separator context
!define _43(context, separator = '') _42(context, separator) separator context
!define _44(context, separator = '') _43(context, separator) separator context
!define _45(context, separator = '') _44(context, separator) separator context
!define _46(context, separator = '') _45(context, separator) separator context
!define _47(context, separator = '') _46(context, separator) separator context
!define _48(context, separator = '') _47(context, separator) separator context
!define _49(context, separator = '') _48(context, separator) separator context
!define _50(context, separator = '') _49(context, separator) separator context
!define _51(context, separator = '') _50(context, separator) separator context
!define _52(context, separator = '') _51(context, separator) separator context
!define _53(context, separator = '') _52(context, separator) separator context
!define _54(context, separator = '') _53(context, separator) separator context
!define _55(context, separator = '') _54(context, separator) separator context
!define _56(context, separator = '') _55(context, separator) separator context
!define _57(context, separator = '') _56(context, separator) separator context
!define _58(context, separator = '') _57(context, separator) separator context
!define _59(context, separator = '') _58(context, separator) separator context
!define _60(context, separator = '') _59(context, separator) separator context
!define _61(context, separator = '') _60(context, separator) separator context
!define _62(context, separator = '') _61(context, separator) separator context
!define _63(context, separator = '') _62(context, separator) separator context
!define _64(context, separator = '') _63(context, separator) separator context
!define _65(context, separator = '') _64(context, separator) separator context
!define _66(context, separator = '') _65(context, separator) separator context
!define _67(context, separator = '') _66(context, separator) separator context
!define _68(context, separator = '') _67(context, separator) separator context
!define _69(context, separator = '') _68(context, separator) separator context
!define _70(context, separator = '') _69(context, separator) separator context
!define _71(context, separator = '') _70(context, separator) separator context
!define _72(context, separator = '') _71(context, separator) separator context
!define _73(context, separator = '') _72(context, separator) separator context
!define _74(context, separator = '') _73(context, separator) separator context
!define _75(context, separator = '') _74(context, separator) separator context
!define _76(context, separator = '') _75(context, separator) separator context
!define _77(context, separator = '') _76(context, separator) separator context
!define _78(context, separator = '') _77(context, separator) separator context
!define _79(context, separator = '') _78(context, separator) separator context
!define _80(context, separator = '') _79(context, separator) separator context
!define _81(context, separator = '') _80(context, separator) separator context
!define _82(context, separator = '') _81(context, separator) separator context
!define _83(context, separator = '') _82(context, separator) separator context
!define _84(context, separator = '') _83(context, separator) separator context
!define _85(context, separator = '') _84(context, separator) separator context
!define _86(context, separator = '') _85(context, separator) separator context
!define _87(context, separator = '') _86(context, separator) separator context
!define _88(context, separator = '') _87(context, separator) separator context
!define _89(context, separator = '') _88(context, separator) separator context
!define _90(context, separator = '') _89(context, separator) separator context
!define _91(context, separator = '') _90(context, separator) separator context
!define _92(context, separator = '') _91(context, separator) separator context
!define _93(context, separator = '') _92(context, separator) separator context
!define _94(context, separator = '') _93(context, separator) separator context
!define _95(context, separator = '') _94(context, separator) separator context
!define _96(context, separator = '') _95(context, separator) separator context
!define _97(context, separator = '') _96(context, separator) separator context
!define _98(context, separator = '') _97(context, separator) separator context
!define _99(context, separator = '') _98(context, separator) separator context
!define _100(context, separator = '') _99(context, separator) separator context

!endif

@enduml
